family <- data.frame(matrix(ncol=2))

colnames(family) <- c("Model", "Family")

family <- rbind(family, c("avNNet_decay1e02", "NNET"))
family <- rbind(family, c("avNNet_decay1e04", "NNET"))
family <- rbind(family, c("bagFDA_prune4", "BAG")) # No apareix en delgado
family <- rbind(family, c("bagFDA_prune8", "BAG"))
family <- rbind(family, c("c5.0", "DT"))
family <- rbind(family, c("c5.0_winnow", "DT"))
family <- rbind(family, c("cforest_mtry16", "RF"))
family <- rbind(family, c("cforest_mtry64", "RF"))
family <- rbind(family, c("ctree_c0.01", "DT"))
family <- rbind(family, c("ctree_c0.05", "DT"))
family <- rbind(family, c("earth", "MARS"))
family <- rbind(family, c("fda_prune17", "DA"))
family <- rbind(family, c("fda_prune9", "DA"))
family <- rbind(family, c("gbm_2_100", "BST"))  # No apareix en Delgado
family <- rbind(family, c("gbm_3_50", "BST"))
family <- rbind(family, c("hdrda", "DA"))
family <- rbind(family, c("Ibk_k3", "NN"))
family <- rbind(family, c("Ibk_k5", "NN"))
family <- rbind(family, c("J48", "DT"))
family <- rbind(family, c("J48Unp", "DT"))
family <- rbind(family, c("JRip", "RL"))
family <- rbind(family, c("JRip_Unp", "RL"))
family <- rbind(family, c("knn_k3", "NN"))
family <- rbind(family, c("knn_k5", "NN"))
family <- rbind(family, c("LMT", "DT"))  # No apareix. O es DT o familia de LR
family <- rbind(family, c("LR", "LMR")) # No apareix, però ha de ser esta
family <- rbind(family, c("lvq_3", "NNET"))
family <- rbind(family, c("lvq_5", "NNET"))
family <- rbind(family, c("mlp_3", "NNET"))
family <- rbind(family, c("mlp_5", "NNET"))
family <- rbind(family, c("mlp_7", "NNET"))
family <- rbind(family, c("mlpML_2", "NNET"))
family <- rbind(family, c("mlpWeightDecay_1e05", "NNET"))
family <- rbind(family, c("mlpWeightDecayML_2_1e05", "NNET"))
family <- rbind(family, c("multinom", "LMR"))
family <- rbind(family, c("NB", "BY"))
family <- rbind(family, c("NB_laplace", "BY"))
family <- rbind(family, c("parRF_mtry16", "RF"))
family <- rbind(family, c("parRF_mtry64", "RF"))
family <- rbind(family, c("PART", "RL"))
family <- rbind(family, c("pda", "DA"))
family <- rbind(family, c("protoclass", "NN"))  #tampoc apareix en delgado, però és el que mes li sembla
family <- rbind(family, c("rbf", "NNET"))
family <- rbind(family, c("rda", "DA"))
family <- rbind(family, c("rf_mtry16", "RF"))
family <- rbind(family, c("rf_mtry64", "RF"))
family <- rbind(family, c("rfRules_mtry16", "RF"))  # El mateix per a estos dos, no apareixen
family <- rbind(family, c("rfRules_mtry64", "RF"))
family <- rbind(family, c("rrf_mtry16", "RF"))
family <- rbind(family, c("rrf_mtry64", "RF"))
family <- rbind(family, c("sda_L1.0", "DA"))
family <- rbind(family, c("simpls_ncomp2", "PLSR"))
family <- rbind(family, c("simpls_ncomp3", "PLSR"))
family <- rbind(family, c("simpls_ncomp4", "PLSR"))
family <- rbind(family, c("svmLinear_C1", "SVM"))
family <- rbind(family, c("svmLinear_C2", "SVM"))
family <- rbind(family, c("svmPoly_d_1_s_0.1", "SVM"))
family <- rbind(family, c("svmPoly_d_2_s_0.1", "SVM"))
family <- rbind(family, c("svmPoly_d_3_s_0.1", "SVM"))
family <- rbind(family, c("svmRadialCost_C2_11", "SVM"))
family <- rbind(family, c("svmRadialCost_C2_5", "SVM"))
family <- rbind(family, c("W_NB", "BY"))
family <- rbind(family, c("Bagging", "BAG"))
family <- rbind(family, c("rpart", "DT"))
family <- rbind(family, c("rbfDDA", "NNET"))

family <- family[2:nrow(family),]
rownames(family) <- NULL
save(family, file="model_families.RData")
save(family, file="/tmp/model_families.RData")
